# Generated by Django 4.2.7 on 2023-11-21 03:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jacare', '0002_customer_restaurant_restaurantuser_restaurantsowned_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='restaurantuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='restaurantuser',
            name='restaurant_user_uid',
        ),
        migrations.AddField(
            model_name='customerreviews',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='customerreviews',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jacare.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='place_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='contact_person',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='restaurant_name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='restaurant_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jacare.customer'),
            preserve_default=False,
        ),
    ]
