# Generated by Django 4.2.7 on 2023-11-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacare', '0003_delete_hello_rename_first_name_customer_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerreviews',
            name='accessibility_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customerreviews',
            name='atmosphere_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customerreviews',
            name='customer_service_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customerreviews',
            name='food_quality_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customerreviews',
            name='value_for_price_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='business_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contact_person',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
