# Generated by Django 4.2.7 on 2023-11-24 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jacare', '0004_alter_customer_birthday_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TierReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_level', models.IntegerField()),
                ('reward_description', models.TextField()),
                ('refresh', models.IntegerField()),
                ('verified_reviwes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=255, unique=True)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('birthday', models.DateField(null=True)),
                ('level', models.IntegerField(null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='visited_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visited', models.DateTimeField(auto_now_add=True)),
                ('saved', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurantsowned',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurantsowned',
            name='restaurant_user',
        ),
        migrations.RemoveField(
            model_name='restaurantuser',
            name='restaurant_user',
        ),
        migrations.RenameField(
            model_name='customerreviews',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='accessibility_comments',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='accessibility_points',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='atmosphere_comments',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='atmosphere_points',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='customer_service_comments',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='customer_service_points',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='food_quality_comments',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='food_quality_points',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='value_for_price_comments',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='value_for_price_points',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='claimed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='retaurant_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customerreviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='RestaurantsOwned',
        ),
        migrations.DeleteModel(
            name='RestaurantUser',
        ),
        migrations.AddField(
            model_name='visited_history',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacare.restaurant'),
        ),
        migrations.AddField(
            model_name='visited_history',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacare.user'),
        ),
        migrations.AddField(
            model_name='tierreward',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacare.restaurant'),
        ),
        migrations.AddField(
            model_name='tier',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacare.restaurant'),
        ),
        migrations.AddField(
            model_name='tier',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacare.user'),
        ),
        migrations.AddField(
            model_name='points',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacare.user'),
        ),
        migrations.AddField(
            model_name='customerreviews',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jacare.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jacare.user'),
        ),
    ]
