# Generated by Django 4.2.7 on 2023-11-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacare', '0006_alter_customerreviews_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visited_history',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
