# Generated by Django 4.2.7 on 2023-11-30 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacare', '0008_restaurant_address_claim_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacare.restaurant')),
            ],
        ),
        migrations.RenameField(
            model_name='tierreward',
            old_name='refresh',
            new_name='points_required',
        ),
        migrations.RemoveField(
            model_name='tierreward',
            name='verified_reviwes',
        ),
        migrations.AddField(
            model_name='customerreviews',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tierreward',
            name='reward_level',
            field=models.CharField(),
        ),
        migrations.DeleteModel(
            name='Tier',
        ),
        migrations.AddField(
            model_name='usertier',
            name='tier_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacare.tierreward'),
        ),
        migrations.AddField(
            model_name='usertier',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacare.user'),
        ),
    ]
