# Generated by Django 4.2.7 on 2023-12-01 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('business', '0002_initial'),
        ('jacare', '0009_usertier_rename_refresh_tierreward_points_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='owner_user_id',
        ),
        migrations.RemoveField(
            model_name='tierreward',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='usertier',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='usertier',
            name='tier_level',
        ),
        migrations.RemoveField(
            model_name='usertier',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='visited_history',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='visited_history',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='customerreviews',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.restaurant'),
        ),
        migrations.AlterField(
            model_name='customerreviews',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.DeleteModel(
            name='claim_requests',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='TierReward',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserTier',
        ),
        migrations.DeleteModel(
            name='visited_history',
        ),
    ]
