# Generated by Django 4.2.7 on 2023-12-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacare', '0010_remove_points_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreviews',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
            preserve_default=False,
        ),
    ]
