# Generated by Django 4.2.7 on 2023-12-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacare', '0011_customerreviews_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreviews',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
