# Generated by Django 4.2.7 on 2023-12-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jacare', '0012_alter_customerreviews_email'),
        ('jacare', '0012_customerreviews_ishidden'),
    ]

    operations = [
    ]
