# Generated by Django 4.2.7 on 2023-12-28 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_restaurant_qr_code_link'),
        ('user', '0006_remove_usertier_tier_level_and_more'),
        ('jacare', '0013_merge_20231208_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
