# Generated by Django 4.2.7 on 2023-12-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
