# Generated by Django 4.2.7 on 2023-12-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationrequests',
            options={'verbose_name_plural': 'Registration Requests'},
        ),
    ]
