# Generated by Django 4.2.7 on 2023-12-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_restaurant_qr_code_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tierreward',
            name='refreshes_in',
            field=models.DateTimeField(null=True),
        ),
    ]
