# Generated by Django 4.2.7 on 2023-12-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_tierreward_refreshes_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.JSONField(default=dict),
        ),
    ]
