# Generated by Django 4.2.7 on 2023-12-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierreward',
            name='reward_level',
            field=models.TextField(),
        ),
    ]
