# Generated by Django 4.2.7 on 2023-12-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='qr_code_link',
            field=models.CharField(default=None, null=True),
        ),
    ]
