# Generated by Django 4.2.7 on 2023-12-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_tierreward_reward_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='qr_code_link',
            field=models.TextField(default=None, null=True),
        ),
    ]
