# Generated by Django 4.2.7 on 2023-12-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_restaurant_qr_code_link'),
        ('business', '0008_alter_restaurant_qr_code_link'),
    ]

    operations = [
    ]
