# Generated by Django 4.2.7 on 2023-12-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_merge_20231211_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierreward',
            name='reward_level',
            field=models.CharField(),
        ),
    ]
