# Generated by Django 4.2.7 on 2023-12-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_tierreward_reward_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tierreward',
            name='refreshes_in',
        ),
        migrations.AddField(
            model_name='tierreward',
            name='refresh',
            field=models.IntegerField(null=True),
        ),
    ]
