# Generated by Django 4.2.7 on 2023-12-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_registrationrequests_options'),
        ('business', '0011_remove_tierreward_refreshes_in_tierreward_refresh'),
    ]

    operations = [
    ]
