# Generated by Django 4.2.7 on 2023-12-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_restaurant_claimed'),
        ('business', '0012_merge_20231211_1911'),
    ]

    operations = [
    ]
