# Generated by Django 4.2.7 on 2023-12-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_restaurant_qr_code_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='qr_code_link',
            field=models.CharField(default=None, null=True),
        ),
    ]
