# Generated by Django 4.2.7 on 2023-12-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertier',
            old_name='expires_at',
            new_name='refeshes_in',
        ),
    ]
