# Generated by Django 4.2.7 on 2023-12-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_expires_at_usertier_refeshes_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertier',
            old_name='refeshes_in',
            new_name='refreshes_in',
        ),
    ]
