# Generated by Django 4.2.7 on 2023-12-07 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_tierreward_refreshes_in'),
        ('user', '0004_rename_refeshes_in_usertier_refreshes_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertier',
            name='refreshes_in',
        ),
        migrations.AddField(
            model_name='usertier',
            name='tier_refreshes_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh', to='business.tierreward'),
        ),
        migrations.AlterField(
            model_name='usertier',
            name='tier_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='business.tierreward'),
        ),
    ]
