# Generated by Django 4.2.7 on 2023-12-07 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_tierreward_refreshes_in'),
        ('user', '0005_remove_usertier_refreshes_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertier',
            name='tier_level',
        ),
        migrations.RemoveField(
            model_name='usertier',
            name='tier_refreshes_in',
        ),
        migrations.AddField(
            model_name='usertier',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.tierreward'),
        ),
    ]
